### PR TITLE
Add Mac OSX target

### PR DESCRIPTION
**Pull request by BobZombie**
SwiftyXMLParser can also be used on OSX, I added a project.
I tested with Carthage.  Sorry, I don't know CocoaPods.

### CODE REVIEW

**Comment by kazuhiro4949** [comment]
Thanks for your pull request! I'll check later :)

**Comment by kazuhiro4949** [comment]
It looks fine 👍 
I have checked unit test working.

**Comment by kazuhiro4949** [comment]
merged.

**Comment by kazuhiro4949** [comment]
I'm sorry for temporary reverting this pull-request, because of build failure to ios app.

**Comment by serluca** [comment]
Any update for Mac OSX?

**Comment by kazuhiro4949** [comment]
@serluca  There is no update for macOS after reverting. I haven't make enough time to check the problem...

**Pull request merged**
